name: SDSkyblockCore
version: '1.0.1-SNAPSHOT'
main: org.sumit282698.sDSkyblockCore.SDSkyblockCore
api-version: '1.21'

commands:
  sdget:
    description: Gives a custom Skyblock item
    usage: /<command> <itemId>
    aliases: [sditem]
    permission: sdskyblock.admin
    permission-message: You don't have permission!

  sdskills:
    description: Add or remove player skills
    usage: /<command> <player> <stat> <amount>
    aliases: [sds]
    permission: sdskyblock.admin
    permission-message: You don't have permission!

  sdprofile:
    description: Opens your Skyblock profile
    usage: /<command>