name: SDSkyblockCore
version: '1.0.1-SNAPSHOT'
main: org.sumit282698.sDSkyblockCore.SDSkyblockCore
api-version: '1.21'

commands:
  sdget:
    description: Get a custom Skyblock item
    usage: /<command> <id>
  sdskills:
    description: add or remove skills
    usage: /<command> <id>